### ISSUE TITLE
Game crashing when entering Gaia portal

### ISSUE THREAD

**Issue by ghost** [Andromander/Gaia-Dimension#62]
Hi. I love your mod! I'm planning on putting it into my modpack Fantastica but the game crashes every time I enter the portal. I first created it in survival mode then, when it crashed, I tested it in creative mode on a new world and it still crashed. Here is the crash report.

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 3/24/20 1:00 PM
Description: Colliding entity with block

java.lang.IllegalAccessError: tried to access field net.minecraft.entity.player.ServerPlayerEntity.field_184851_cj from class androsa.gaiadimension.block.GaiaPortalBlock
	at androsa.gaiadimension.block.GaiaPortalBlock.changeDimension(GaiaPortalBlock.java:148) ~[?:1.14.4-1.1.2] {re:classloading}
	at androsa.gaiadimension.block.GaiaPortalBlock.func_196262_a(GaiaPortalBlock.java:134) ~[?:1.14.4-1.1.2] {re:classloading}
	at net.minecraft.block.BlockState.func_196950_a(BlockState.java:262) ~[?:?] {re:classloading}
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:838) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:generic-update-hook,xf:fml:quark:override-collision}
	at net.minecraft.entity.Entity.func_213315_a(Entity.java:572) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:quark:generic-update-hook,xf:fml:quark:override-collision}
	at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntity.java:1829) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothpotiondmg}
	at net.minecraft.entity.player.PlayerEntity.func_213352_e(PlayerEntity.java:1453) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:backpacked:player_init_hook}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2214) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothpotiondmg}
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:494) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:backpacked:player_init_hook}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2032) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothpotiondmg}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:backpacked:player_init_hook}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:365) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:backpacked:creative_inventory_action_fix}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at androsa.gaiadimension.block.GaiaPortalBlock.changeDimension(GaiaPortalBlock.java:148)
	at androsa.gaiadimension.block.GaiaPortalBlock.func_196262_a(GaiaPortalBlock.java:134)
	at net.minecraft.block.BlockState.func_196950_a(BlockState.java:262)

-- Block being collided with --
Details:
	Block: Block{gaiadimension:gaia_portal}[axis=z]
	Block location: World: (-226,88,146), Chunk: (at 14,5,2 in -15,9; contains blocks -240,0,144 to -225,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:838)

-- Entity being checked for collision --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 351
	Entity Name: Tripwolf
	Entity's Exact location: -225.68, 88.00, 146.51
	Entity's Block location: World: (-226,88,146), Chunk: (at 14,5,2 in -15,9; contains blocks -240,0,144 to -225,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.func_213315_a(Entity.java:572)
	at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntity.java:1829)
	at net.minecraft.entity.player.PlayerEntity.func_213352_e(PlayerEntity.java:1453)
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2214)
	at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:494)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2032)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:232)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 351
	Entity Name: Tripwolf
	Entity's Exact location: -225.68, 88.00, 146.51
	Entity's Block location: World: (-226,88,146), Chunk: (at 14,5,2 in -15,9; contains blocks -240,0,144 to -225,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:365)
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:183)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:228)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@60bd38f4
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2057717576 bytes (1962 MB) / 4061659136 bytes (3873 MB) up to 7458521088 bytes (7113 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8001m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.3.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.3
	FML Language Providers: 
		javafml@28.2
		minecraft@1
		kotlinfml@1.4.0
	Mod List: 
		Cucumber-1.14.4-2.0.6.jar Cucumber Library {cucumber@2.0.6 DONE}
		damage_indicator-0.0.8.jar Ama's Damage Indicator {damage_indicator@0.0.8 DONE}
		Wyrmroost-1.14.4-1.0.2.jar Wyrmroost {wyrmroost@1.0.2 DONE}
		vilnames_1.14-2.0.jar Villager Names {vilnames@2.0 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		Druidcraft-1.14-0.3.1.jar Druidcraft {druidcraft@0.3.1 DONE}
		FallingTree-1.14.4-2.0.3+21.jar Falling Tree {falling_tree@2.0.3+21 DONE}
		Upgrade-Aquatic-1.14.4-v1.4.10.jar Upgrade Aquatic {upgrade_aquatic@1.4.9 DONE}
		bloomful-1.2.4.jar Bloomful {bloomful@1.2.3 DONE}
		Vulcanite-2.0.3-mc1.14.4.jar Vulcanite {vulcanite@2.0.3-mc1.14.4 DONE}
		Pam's BoneCraft 1.14.4-1.0.0.jar Pam's BoneCraft {bonecraft@version DONE}
		journeymap-1.14.4-5.7.0b1.jar Journeymap {journeymap@1.14.4-5.7.0b1 DONE}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 DONE}
		comforts-FORGE-1.14.4-2.0-beta6.jar Comforts {comforts@FORGE-1.14.4-2.0-beta6 DONE}
		citadel-1.0.0.jar Citadel {citadel@1.0.0 DONE}
		good-nights-sleep-1.14.4-1.0.2.jar Good Night's Sleep {goodnightsleep@1.0.2 DONE}
		SereneSeasons-1.14.4-2.0.0.40-universal.jar Serene Seasons {sereneseasons@1.14.4-2.0.0.40 DONE}
		firefly-1.14.4-1.0.1.jar Firefly {firefly@1.14.4-1.0.1 DONE}
		DungeonCrawl-1.14.4-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		betteranimalsplus-1.14.4-8.2.1.jar Better Animals Plus {betteranimalsplus@8.2.1 DONE}
		The-Endergetic-Expansion-1.14.4-v1.2.0.jar The Endergetic Expansion {endergetic@1.2.0 DONE}
		Apotheosis-1.14.4-2.4.4.jar Apotheosis {apotheosis@2.4.4 DONE}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version DONE}
		mysticalworld-1.14.4-1.7.2.jar Mystical World {mysticalworld@1.14.4-1.7.2 DONE}
		forge-1.14.4-28.2.3-universal.jar Forge {forge@28.2.3 DONE}
		ruins-1.14.4.6.jar Ruins {ruins@1.14.4.6 DONE}
		mysticallib-1.14.4-1.14.0.jar Mystical Lib {mysticallib@1.14.4-1.14.0 DONE}
		MysticalAgriculture-1.14.4-2.0.6.jar Mystical Agriculture {mysticalagriculture@2.0.6 DONE}
		villagerdeathm_1.14-1.2.jar Villager Death Messages {villagerdeathm@1.2 DONE}
		koratio-1.14.4-0.0.9-beta.jar Koratio {koratio@1.14.4-0.0.9-beta DONE}
		forge-1.14.4-28.2.3-client.jar Minecraft {minecraft@1.14.4 DONE}
		torchmaster-2.0.0-rc2.jar Torchmaster {torchmaster@2.0.0-rc2 DONE}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 DONE}
		pandoras_creatures-1.14.4-0.12.0.jar Pandoras Creatures {pandoras_creatures@1.14.4-0.12.0 DONE}
		illuminations-0.1.0-1.14.4.jar Illuminations for Forge {illuminations@1.0.0.0 DONE}
		simpleworldtimer-1.14.4-1.1.2-beta.jar Simple World Timer {simpleworldtimer@1.14.4-1.1.2-beta DONE}
		BiomesOPlenty-1.14.4-9.0.0.262-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.259 DONE}
		seafaring-1.14.4-0.2.1.jar Seafaring {sea@0.2.1 DONE}
		forbidden_arcanus-1.14.4-1.5.jar Forbidden & Arcanus {forbidden_arcanus@1.14.4-1.5 DONE}
		extcaves-1.5.jar Extended Caves {extcaves@1.5 DONE}
		villagesp_1.14-1.0.jar Village Spawn Point {villagesp@1.0 DONE}
		lycanitesmobs-1.14.4-2.1.4.4.jar Lycanites Mobs {lycanitesmobs@1.0 DONE}
		Kathairis-1.14.4-alpha-0.16.jar Kathairis {kathairis@version DONE}
		gaiadimension-1.14.4-1.1.2.jar The Gaia Dimension {gaiadimension@1.1.2 DONE}
		curios-FORGE-1.14.4-1.0.6.1.jar Curios API {curios@FORGE-1.14.4-1.0.6.1 DONE}
		Botania r1.11-378.jar Botania {botania@r1.11-378 DONE}
		Patchouli-1.14.4-1.1-26.jar Patchouli {patchouli@1.14.4-1.1-25 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		OreExcavation-1.6.147.jar Ore Excavation {oreexcavation@NONE DONE}
		angelring-1.1.0.jar Angel Ring {angelring@1.1.0 DONE}
		backpacked-1.4.0-1.14.4.jar Backpacked {backpacked@1.4.0 DONE}
		themidnight-0.4.6.jar The Midnight {midnight@0.4.6 DONE}
		tombstone-4.3.0-1.14.4.jar Corail Tombstone {tombstone@4.3.0 DONE}
		Quark-r2.0-212.jar Quark {quark@r2.0-212 DONE}
		EnigmaticLegacy-1.6.4.jar Enigmatic Legacy {enigmaticlegacy@1.6.4 DONE}
		NaturesAura-20.3.jar Nature's Aura {naturesaura@version DONE}
		AppleSkin-mc1.14.4-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		Aquaculture-1.14.4-2.0.7.jar Aquaculture 2 {aquaculture@1.14.4-2.0.7 DONE}
		XL-Food-Mod-1.14.4-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 DONE}
		CHAS v1.3 for 1.14.jar Craftable Horse Armour {craftablehorsearmour@1.3 DONE}
		Charm-1.14.4-1.5.3.jar Charm {charm@1.14.4-1.5.3 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['Tripwolf'/351, l='New World', x=-225.68, y=88.00, z=146.51]]
	Data Packs: vanilla, mod:angelring, mod:apotheosis, mod:appleskin, mod:aquaculture, mod:arl, mod:backpacked, mod:betteranimalsplus, mod:biomesoplenty, mod:bloomful, mod:bonecraft, mod:botania, mod:charm, mod:citadel, mod:comforts, mod:craftablehorsearmour, mod:cucumber, mod:curios, mod:damage_indicator, mod:druidcraft, mod:dungeoncrawl, mod:endergetic, mod:enigmaticlegacy, mod:extcaves, mod:falling_tree, mod:firefly, mod:forbidden_arcanus, mod:forge, mod:gaiadimension, mod:goodnightsleep, mod:illuminations, mod:jei, mod:journeymap, mod:kathairis, mod:koratio, mod:lycanitesmobs, mod:midnight, mod:mysticalagriculture, mod:mysticallib, mod:mysticalworld, mod:naturesaura, mod:oreexcavation, mod:pandoras_creatures, mod:patchouli, mod:placebo, mod:quark, mod:ruins, mod:sea, mod:sereneseasons, mod:simpleworldtimer, mod:swingthroughgrass, mod:tombstone, mod:torchmaster, mod:upgrade_aquatic, mod:villagerdeathm, mod:villagesp, mod:vilnames, mod:vulcanite, mod:waila, mod:wyrmroost, mod:xlfoodmod
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Andromander** [comment]
Known issue, however, I do not actively work on 1.14 as I have now moved to 1.15. This is partly due to the required teleporting logic not being available until 1.15, as well as not having an environment to build with 1.14. Known solutions are using a teleport command or another mod that handles teleporting. 

I will keep this open in case anyone else is able to make a release that fixes the portal, as I cannot.

**Comment by H4Mm3r** [comment]
Oh, sad news, same issue here. Would really love this fix. Thanks by advance.

**Comment by Andromander** [comment]
Issue has now been resolved as of 1.1.3.
